[package]
name = "apollo-rust-planning"
version = "0.1.0"
edition = "2021"

[dependencies]
apollo-rust-robotics = { path = "../apollo-rust-robotics" }
apollo-rust-robotics-core = { path = "../apollo-rust-robotics-core" }
apollo-rust-linalg = { path = "../apollo-rust-linalg" }