[package]
name = "apollo_rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/apollo_file",
    "crates/apollo_linalg",
    "crates/apollo_spatial",
    "crates/apollo_robotics"
, "crates/apollo_lie"]

[dependencies]



[lib]
name = "apollo_rust"
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
# lto = "thin"