[package]
name = "apollo-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/apollo-file",
    "crates/apollo-linalg",
    "crates/apollo-spatial",
    "crates/apollo-lie",
    "crates/apollo-proximity",
    "crates/apollo-file-py"
]

[dependencies]



[lib]
name = "apollo_rust"
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
# lto = "thin"