[package]
name = "apollo-file-py"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "apollo_file_py"
crate-type = ["cdylib"]

[dependencies]
apollo-file = { path = "../apollo-file" }
pyo3 = "0.22.0"
