[package]
name = "apollo_spatial"
version = "0.1.0"
edition = "2021"

[dependencies]
apollo_linalg = { path="../apollo_linalg" }
nalgebra = { version = "0.32.6", features = ["rand"] }
rand = { version="0.9.0-alpha.1" }
