[package]
name = "apollo-rust-robot-modules"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version="1.0.204", features = ["derive"] }
serde_json = { version="1.0.120" }
urdf-rs = { version="0.8.0" }
rand = "0.9.0-alpha.1"
